baseURL = "https://icfree.org/"
languageCode = "en-us"
title = "iCFree"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    description = "Improved cell-free systems to accelerate therapeutic proteins production at minimal cost"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!!

[module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"

[[menu.main]]
    url = "/home/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/partners/"
    name = "Partners"
    weight = 2

[[menu.main]]
    url = "/news/"
    name = "News"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "fab fa-twitter"
    weight = 1